src/Entity/Prestation.php
<?php

namespace App\Entity;

use App\Repository\PrestationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PrestationRepository::class)]
class Prestation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $Nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Extrait = null;

    #[ORM\Column(length: 200)]
    private ?string $Description = null;

    #[ORM\Column]
    #[Assert\Range(
        min: 5,
        max: 500,
        notInRangeMessage: 'La rénumération doit être comprise entre {{ min }} et {{ max }} €',
    )]
    private ?float $Renumeration = null;

    #[ORM\ManyToOne(inversedBy: 'prestations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getExtrait(): ?string
    {
        return $this->Extrait;
    }

    public function setExtrait(string $Extrait): static
    {
        $this->Extrait = $Extrait;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getRenumeration(): ?float
    {
        return $this->Renumeration;
    }

    public function setRenumeration(float $Renumeration): static
    {
        $this->Renumeration = $Renumeration;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }
}

src/Form/PrestationType.php
<?php

namespace App\Form;

use App\Entity\Prestation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
//use Symfony\Component\Form\Extension\Core\Type\RepeatedType;

class PrestationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Extrait')
            ->add('Description')
            ->add('Renumeration')

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Prestation::class,
        ]);
    }
}

src/Controller/PrestationController.php
<?php

namespace App\Controller;
use App\Form\PrestationType;
use App\Entity\Prestation;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\PrestationRepository;

class PrestationController extends AbstractController
{
    #[Route('/prestation', name: 'app_prestation')]
    public function index(PrestationRepository $PrestationRepository): Response
    {
        $prestations = $PrestationRepository->findAll();
        return $this->render('prestation/index.html.twig', [
            'prestations' => $prestations,
        ]);
}
   #[Route('/register_prestation', name: 'app_register_prestation')]
   public function register_prestation(Request $request, EntityManagerInterface $entityManager): Response
   {
       $prestation = new Prestation();
       $form = $this->createForm(PrestationType::class, $prestation);
       $form->handleRequest($request);

       if ($form->isSubmitted() && $form->isValid()){
           $entityManager->persist($prestation);
           $entityManager->flush();

           $this->addFlash(
               'notice',
               'Your changes were saved!'
           );

           return $this->redirectToRoute('app_prestation');

       }

       return $this->render('prestation/register_prestation.html.twig',
       [
           'form' => $form,
       ]);

   }
}

templates/prestation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Prestations{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <!-- Partie de gauche - Les 10 dernières prestations -->
            <div class="col-md-6">
                <h2>Les dernières prestations</h2>
                {% for prestation in prestations %}
                <ul class="list-group">
                    <li class="list-group-item">{{ prestation.Nom }} - {{ prestation.User.prenom }} - {{ prestation.Renumeration }}€</li>
                </ul>
                {% endfor %}
            </div>

            <!-- Partie de droite - Dernier utilisateur enregistré -->
            <div class="col-md-6">
                <h2>Dernier utilisateur enregistré</h2>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ app.user.nom }}</h5>
                        <p class="card-text">{{ app.user.email }}</p>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/prestation/register_prestation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rajoute ta prestation{% endblock %}

{% block body %}
    <div class="container w-25 m-auto">
    {{ form_start(form) }}
        {{ form_row(form.Nom) }}
        {{ form_row(form.Extrait) }}
        {{ form_row(form.Description) }}
        {{ form_row(form.Renumeration) }}
    <button type="submit" class="btn btn-primary">Ajouter</button>
    {{ form_end(form) }}
    </div>
{% endblock %}