src/Entity/Prestation.php
<?php

namespace App\Entity;

use App\Repository\PrestationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PrestationRepository::class)]
class Prestation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $Nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Extrait = null;

    #[ORM\Column(length: 200)]
    private ?string $Description = null;

    #[ORM\Column]
    #[Assert\Range(
        min: 5,
        max: 500,
        notInRangeMessage: 'La rénumération doit être comprise entre {{ min }} et {{ max }} €',
    )]
    private ?float $Renumeration = null;

    #[ORM\ManyToOne(inversedBy: 'prestations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getExtrait(): ?string
    {
        return $this->Extrait;
    }

    public function setExtrait(string $Extrait): static
    {
        $this->Extrait = $Extrait;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getRenumeration(): ?float
    {
        return $this->Renumeration;
    }

    public function setRenumeration(float $Renumeration): static
    {
        $this->Renumeration = $Renumeration;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }
}

src/Controller/JeuxController.php
<?php

namespace App\Controller;


use App\Entity\Jeu;
use App\Form\JeuType;
use App\Repository\JeuRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class JeuxController extends AbstractController
{
    #[Route('/jeux', name: 'app_jeux')]
    public function index(JeuRepository $jeuRepository): Response
    {
        $jeux = $jeuRepository->findJeuxWithLimitedNumber(3);


        return $this->render('jeux/index.html.twig', [
           'jeux' => $jeux
        ]);


    }
    #[Route('/admin/jeux', name: 'app_admin_jeux')]
    public function jeux_admin(JeuRepository $jeuRepository): Response
    {
        $jeux = $jeuRepository->findAll();


        return $this->render('admin/jeux/index.html.twig', [
            'jeux' => $jeux
        ]);
    }

    #[Route('jeu/ajouter', name: 'app_admin_jeux_ajouter')]
    #[Route('jeu/modifier/{id}', name: 'app_admin_jeux_modifier')]
    public function editer(Request $request,JeuRepository $jeuRepository, EntityManagerInterface $entityManager, int $id = null): Response
    {

        if($request->attributes->get('_route') == 'app_admin_jeux_ajouter'){
            $jeux = new Jeu();
        }else{
            $jeux = $jeuRepository->find($id);
        }

        $form = $this->createForm(JeuType::class, $jeux);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $entityManager->persist($jeux);
            $entityManager->flush();


            if($request->attributes->get('_route') == 'app_admin_jeux_ajouter'){
                $this->addFlash(
                    'success',
                    'Le nouveau jeu a bien été ajouté !'
                ); }else{
                $this->addFlash(
                    'success',
                    'Le jeu a bien été modifié !'
                );
            }

            return $this->redirectToRoute('app_admin_jeux');


        }


        return $this->renderForm('admin/jeux/editer.html.twig', [
            'form' => $form
        ]);

    }



    #[Route('/supprimer/{id}', name: 'app_admin_jeux_supprimer')]
    public function supprimer(JeuRepository $jeuRepository, EntityManagerInterface $entityManager, int $id): Response
    {

        $jeux = $jeuRepository->find($id);
        $entityManager->remove($jeux);
        $entityManager->flush();

        $this->addFlash(
            'success',
            "Le jeux a bien été supprimé !"
        );

        return $this->redirectToRoute('app_admin_jeux');



    }

    #[Route('/voir/{id}', name: 'jeu_voir')]
    public function voir(JeuRepository $jeuRepository, int $id): Response
    {
        $jeu = $jeuRepository->find($id);

        return $this->render('jeux/voir.html.twig', [
            'jeu' => $jeu
        ]);
    }

}

templates/jeux/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello JeuxController!{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('accueil') }}
{% endblock %}

{% block body %}
    <div class="container mt-5">
    <h1 class="text-center mt-5" >Bienvenue sur LocaJeu</h1>
        <p class="text-center">Louez mes jeux de société</p>

        <div class="d-flex justify-content-between flex-wrap mt-4">
            {% for jeu in jeux %}
                <div class="card mt-3" style="width: 18rem;">

                    <div class="card-body">
                        <h5 class="card-title">{{ jeu.nom }}</h5>
                        <p class="card-title jeu__genre" style="background-color: {{ jeu.genre.couleur }}">{{ jeu.genre.nom }}</p>
                        <p class="card-text">{{ jeu.description }}</p>
                        <a href="{{ path('jeu_voir', {'id' : jeu.id}) }}" class="btn btn-primary btn-sm">Voir le jeu</a>
                    </div>
                </div>
            {% endfor %}

        </div>

    </div>
{% endblock %}

templates/jeux/voir.html.twig
{% extends 'base.html.twig' %}

{% block title %}LocaJeu - {{ jeu.nom }}
{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1>Le jeu : {{ jeu.nom }}</h1>
        <p><small>Genre : {{ jeu.genre.nom | lower  }} - popularité : {{ jeu.genre.popularite }}</small></p>
        <p>{{ jeu.description }}</p>
    </div>
{% endblock %}